### ISSUE TITLE
Can't save changes on commit to a new image.

### ISSUE THREAD

**Issue by Crare** [tum-gis/3dcitydb-docker-compose#1] opened 2018-08-07 12:20 UTC
I've tried to make changes to this docker, but it seems that any changes I make will not be saved on docker commit. Is this intentional or what am I doing wrong maybe?

friend told me it has something to do with the kernel crashing and setting everything read-only..

Example of what I do:
(container_name and image_name will be replaced with existing wfs, web-map and citydb names.)

```
docker commit container_name image_name

docker tag image_name repository:port/image_name

docker push repository:port/image_name

docker pull repository:port/image_name

docker run repository:port/image_name
```

**Comment by BWibo** [comment] 2018-08-07 13:26
Hey there, this behavior is not intentional. Can you provide more details so I can reproduce the error:

- What image:tag are you using?
- What changes do you make?
- Docker version info?

However, the usage of `docker commit` to create new images is **not recommended**, as the changes you make are not reproducible (e.g. see [here](https://developers.redhat.com/blog/2016/02/24/10-things-to-avoid-in-docker-containers/)). I suggest to make the changes in the `DOCKERFILE` and build the customized image using `docker build`. 

I just tried this:

1. Run WFS Container:
`docker run -it --name wfs tumgis/3dcitydb-wfs bash`
2. Create a test file in the container:
   ```bash
    cd /
    touch test.txt
    echo "this is a test" >> test.txt
    exit
   ```
3. Commit to new image and run new image:

   ```bash
   docker commit wfs testimg
   docker run -it --name changedwfs testimg bash
   ```
4. See, if changes are I made are present:

   ```bash
   cd /
   cat test.txt
   # Output: this is a test
   ```

Hence, the changes I made are saved in the new image.

**Comment by Crare** [comment] 2018-08-08 05:54
I tried what you your way and it worked. But I don't know why what I'm doing doesn't.

I'm creating dockers by running that
`docker-compose up -d`

then copying local www-folder version of nodejs and cesium files to webmap container from local directory.
`docker cp .\www\ default_citydb-web-map_1:/var/`

restarting container so I can see changes in browser http://localhost/3dwebclient/:
`docker restart default_citydb-web-map_1`

saving it with commit
`docker commit default_citydb-web-map_1 webmap`

stopping current webmap container
`docker stop default_citydb-web-map_1`

running the one from images and going to browser http://localhost/3dwebclient/.
`docker run -u 0 -dit --name webmap -p 80:8000 -v C:/docker/data:/var/www/data webmap`

I can't see any changes. This commit was made while running the container. I'll try commit stopped container next.

Everything else same except stopping webmap container before copying files to it.
still doesn't work..
`docker stop default_citydb-web-map_1`

Might be problem with Docker for Windows too..

Or maybe www-folder ect. is somehow read-only or something?

**Comment by Crare** [comment] 2018-08-08 06:24
I tried adding test.txt file inside / and /var/www/ directory and commit to a new image and run it. I did see the test.txt file at / but not in /var/www/.

Maybe volume is messing up any changes inside /var/www/?  but shouldn't it only affect /var/www/data/ directory?

EDIT: maybe not. I tried running container without volume and making changes and committing and running the new image but changes are still not there.

**Comment by BWibo** [comment] 2018-08-08 07:27
I am assuming you are working with the WebClient image and you are mounting `/var/www` inside the container in some way. It is verly likely that your issue is cause by mounting this folder.

Docker behaves *differently* regarding *data storage and persistence* than one might expect in the frist place. Please go through the [docs on managing data in Docker](https://docs.docker.com/storage/). The different storage strategies are explained there in detail. I put together a a brief summary regarding this  [here](https://github.com/tum-gis/3dcitydb-docker-postgis#data-storage-and-persistence) as well. That might be helpful too.

Closing, as this issue seems to be related to Docker data management and not the content of this repo. Feel free to re-open if questions linked to the content in here arise.

**Closed as completed by BWibo** 2018-08-08 07:27 UTC

**Comment by Crare** [comment] 2018-08-08 08:03
I don't think it's about volume I'm using. volume is binded to C:/docker/data:/var/www/data
I'm not editing anything inside /var/www/data, only /var/www/server.js and files under /var/www/3dwebclient they are not under that data-directory. Edits show up after copying them. but not after committing and running that committed image as container. Could you please try adding/editing file under /var/www/ and commit it and try running it to see if it was saved?

**Comment by BWibo** [comment] 2018-08-08 08:43
Hey there, can you please post the full `docker run` command you are using and some information on your system (Docker host operating system, Docker version).

**Comment by Crare** [comment] 2018-08-08 09:03
docker run command: 
`docker run -u 0 -dit --name webmap -p 80:8000 -v C:/docker/data:/var/www/data webmap`

docker version:
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

Host operating system is Windows 10 Enterprise.

I do appreciate that you try to help. Thanks.

**Comment by BWibo** [comment] 2018-08-08 09:51
Lets's continue this where it belongs:
tum-gis/3dcitydb-web-map-docker#2
